# Generated by Django 4.2.6 on 2023-11-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_education_resume_giao_duc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='Giao_Duc',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='Kinh_Nghiem',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='Ho_Ten',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='So_Dien_Thoai',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='Ky_Nang',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='Tom_Tat',
            new_name='summary',
        ),
    ]
