# Generated by Django 4.2.6 on 2023-11-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_giao_duc_resume_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='full_name',
            new_name='Ho_Ten',
        ),
    ]
