# Generated by Django 4.2.6 on 2023-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_education_resume_giao_duc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='Giao_Duc2',
            field=models.CharField(default='Trung Học Cơ Sở Thị Trấn Cầu Ngang', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='Giao_Duc3',
            field=models.CharField(default='Trung Tâm Giáo Dục Thường Xuyên và Dạy Nghề huyện Cầu Ngang', max_length=100),
        ),
    ]
